#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ChordHelper.Resource", IsApplication=true)]

namespace ChordHelper
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int roots = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Chord = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int icon_wavy_staff = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09001f
			public const int aButton = 2131296287;
			
			// aapt resource value: 0x7f090000
			public const int aboutTextView = 2131296256;
			
			// aapt resource value: 0x7f09002b
			public const int action_about = 2131296299;
			
			// aapt resource value: 0x7f09002c
			public const int action_settings = 2131296300;
			
			// aapt resource value: 0x7f09000b
			public const int augmentedTriadRadioButton = 2131296267;
			
			// aapt resource value: 0x7f090020
			public const int bButton = 2131296288;
			
			// aapt resource value: 0x7f09001a
			public const int cButton = 2131296282;
			
			// aapt resource value: 0x7f090024
			public const int checkSpellingButton = 2131296292;
			
			// aapt resource value: 0x7f090014
			public const int chordNameTextView = 2131296276;
			
			// aapt resource value: 0x7f090015
			public const int chordSpellingTextView = 2131296277;
			
			// aapt resource value: 0x7f09001b
			public const int dButton = 2131296283;
			
			// aapt resource value: 0x7f09000c
			public const int diminishedTriadRadioButton = 2131296268;
			
			// aapt resource value: 0x7f090010
			public const int dominant7RadioButton = 2131296272;
			
			// aapt resource value: 0x7f090029
			public const int dummyTextView = 2131296297;
			
			// aapt resource value: 0x7f09001c
			public const int eButton = 2131296284;
			
			// aapt resource value: 0x7f09001d
			public const int fButton = 2131296285;
			
			// aapt resource value: 0x7f090022
			public const int flatButton = 2131296290;
			
			// aapt resource value: 0x7f09002a
			public const int fragContainer = 2131296298;
			
			// aapt resource value: 0x7f090012
			public const int fullyDim7RadioButton = 2131296274;
			
			// aapt resource value: 0x7f09001e
			public const int gButton = 2131296286;
			
			// aapt resource value: 0x7f090011
			public const int halfDim7RadioButton = 2131296273;
			
			// aapt resource value: 0x7f090007
			public const int linearLayout1 = 2131296263;
			
			// aapt resource value: 0x7f090004
			public const int linearLayout2 = 2131296260;
			
			// aapt resource value: 0x7f090016
			public const int linearLayout3 = 2131296278;
			
			// aapt resource value: 0x7f090017
			public const int linearLayout4 = 2131296279;
			
			// aapt resource value: 0x7f090028
			public const int linearLayout5 = 2131296296;
			
			// aapt resource value: 0x7f09000e
			public const int major7RadioButton = 2131296270;
			
			// aapt resource value: 0x7f090009
			public const int majorTriadRadioButton = 2131296265;
			
			// aapt resource value: 0x7f09000f
			public const int minor7RadioButton = 2131296271;
			
			// aapt resource value: 0x7f09000a
			public const int minorTriadRadioButton = 2131296266;
			
			// aapt resource value: 0x7f090018
			public const int newChordButton = 2131296280;
			
			// aapt resource value: 0x7f090019
			public const int newChordTextView = 2131296281;
			
			// aapt resource value: 0x7f090027
			public const int resultTextView = 2131296295;
			
			// aapt resource value: 0x7f090003
			public const int rootSpinner = 2131296259;
			
			// aapt resource value: 0x7f09000d
			public const int seventhsRadioGroup = 2131296269;
			
			// aapt resource value: 0x7f090021
			public const int sharpButton = 2131296289;
			
			// aapt resource value: 0x7f090026
			public const int showAnswerButton = 2131296294;
			
			// aapt resource value: 0x7f090006
			public const int showSeventhsButton = 2131296262;
			
			// aapt resource value: 0x7f090013
			public const int showSpellingButton = 2131296275;
			
			// aapt resource value: 0x7f090005
			public const int showTriadsButton = 2131296261;
			
			// aapt resource value: 0x7f090023
			public const int spellingTextView = 2131296291;
			
			// aapt resource value: 0x7f090002
			public const int textView1 = 2131296258;
			
			// aapt resource value: 0x7f090001
			public const int theoryTrainerButton = 2131296257;
			
			// aapt resource value: 0x7f090008
			public const int triadsRadioGroup = 2131296264;
			
			// aapt resource value: 0x7f090025
			public const int tryAgainButton = 2131296293;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int FragmentAbout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int FragmentChordGenerator = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int FragmentChordTrainer = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int ActionBarMenu = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070002
			public const int AccidentalButton = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int AppTheme = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int NoteButton = 2131165185;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int Preferences = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
